# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
