# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(default='images/noimagefound.jpg', upload_to='news')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(default='images/noimagefound.jpg', upload_to='news')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(default='images/noimagefound.jpg', upload_to='news')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('salary', models.IntegerField(default=0)),
                ('company', models.CharField(default='', max_length=64)),
                ('city', models.CharField(default='', max_length=64)),
                ('address', models.CharField(default='', max_length=128)),
                ('experience', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
