# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacanse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=100)),
                ('company', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=80)),
                ('salary', models.IntegerField(default=0)),
                ('experience', models.CharField(default='', max_length=10)),
                ('text', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
