# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacanse',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vacanse',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vacanse',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vacanse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacanse',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='vacanse',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='vacanse',
            name='text',
        ),
    ]
