# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0002_auto_20170313_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacanse',
            name='address',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='vacanse',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vacanse',
            name='company',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vacanse',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vacanse',
            name='experience',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vacanse',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacanse',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='vacanse',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
