# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0003_auto_20170313_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='adv/shop')),
                ('text', models.CharField(default='', max_length=500)),
                ('cost', models.ImageField(default=0, upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
